---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy a environment (excluding persistence layer and networking)"
Parameters:
  BaseDomainName:
    Type: String
    Default: jollycoding.com
    Description: "Base domain name (e.g.: example.com)"
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair to use when creating EC2 instances
  EnvironmentName:
    Type: String
    Description: "Name of the environment (e.g.: dev, prod)"
  EnvironmentType:
    Type: String
    Description: "Type of environment"
    Default: nonprod
    AllowedValues:
      - prod
      - nonprod
  InstanceType:
    Type: String
    Description: Type of instance to use for application servers
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.medium
      - t3.large
  #########################
  # PHP API               #
  #########################
  PhpApi:
    Type : AWS::EC2::Instance,
    Properties:
      Parameters:
        BaseDomainName: !Ref BaseDomainName
        EC2KeyPair: !Ref EC2KeyPair
        EnvironmentName: !Ref EnvironmentName
        EnvironmentType: !Ref EnvironmentType
        InstanceType: !Ref InstanceType
      TemplateURL: php-api.yaml